apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
